### ISSUE TITLE
Wholesale vs List by Cost

### ISSUE THREAD

**Issue by ahouts** [houtsandrew/CIS22B_FinalProject#103]
@scrable 
They do present the same information, so I guess one is sorted and one isn't... 

On another note, since your module is done, all that you have to do now is finding and fixing bugs. We want to make sure that everywhere you go the user interface is consistent and only displays the information that is needed, so anything you can do to clean up the visuals of other modules would be appreciated.

The teacher also mentioned that we could/should have additional things to separate our project from the rest, but that should be our lowest priority.

**Comment by scrable** [comment]
To be honest I doubt any of the other groups will have anything that resembles ours since our approach seemed very good. 

I'll look around and see if I can improve anything though.

**Comment by ahouts** [comment]
Yeah, mostly we need to work on presentation and bug-fixing now. If you get the chance you should try every option in every menu at least once. Also test incorrect options in the menus, like a 7 if the options are 1-5 or a string instead of a number. We need to make sure that Goel doesn't get into one of those endless loops while using it, that would be bad.

Other than that good work everyone, looks like it will be done on time.

**Comment by scrable** [comment]
Went through all the screens and all work fine when entering valid responses. I'll go through it tomorrow and check invalid responses as well for everything.
