### ISSUE TITLE
Problem with sorting by quantity

### ISSUE THREAD

**Issue by scrable** [houtsandrew/CIS22B_FinalProject#84]
I need help with figuring out how to track quantity of a book. I can't find a good place to add it and have it work well with our implementation. I can't track it currently nor store it anywhere. I don't really know how we're currently tracking multiple copies of books, if we even are.

**Comment by scrable** [comment]
Just thought of an idea while going to sleep, I'll try it in the morning.

**Comment by ahouts** [comment]
![the master plan](https://cloud.githubusercontent.com/assets/16907671/13724367/ed0e9efe-e837-11e5-8dbf-740324e1c55f.png)

This is my idea of how it could be done. There might be an easier way, but I think this would work

**Comment by ahouts** [comment]
you would obviously would want to delete[] bookCount after you were done with it

**Comment by scrable** [comment]
In the project description that he gave us, he said that the ISBN is unique to each book.

http://i.imgur.com/9Bi227B.png

I'm going to assume that I can just track quantity by searching for the same ISBN for each book.

**Comment by ahouts** [comment]
Definition: The purpose of the ISBN is to establish and identify one title or edition of a title from one specific publisher and is unique to that edition, allowing for more efficient marketing of products by booksellers, libraries, universities, wholesalers and distributors.

I think that he means that each edition of book has a unique ISBN, not every single book.

**Comment by ahouts** [comment]
I will write him an email asking about this, because all of the code we have so far assumes that ISBN's are not unique to each book. It is what we have book identifiers for.

**Comment by scrable** [comment]
The way you have the current identifier has it assigned to each individual book, regardless of whether or not there is a copy.

Ex: Five of the same book are in the database file. They will have identifiers of 1-5. But there will be 5 copies of the book. There is no way to track copies like this just based off the identifier alone.
