### ISSUE TITLE
Adding multiple books to inventory

### ISSUE THREAD

**Issue by scrable** [houtsandrew/CIS22B_FinalProject#88]
When adding a large amount of the same book to the inventory via the menu "Add a Book", entering a large number such as 1000 takes a very long time to create the text file. I haven't tested it much but I believe it's due to repeated deleting and copying back and forth from *.txt and the *.txt.bak file. Not really a big issue, but it might be something we can fix later if we find the time.

**Comment by ahouts** [comment]
Yeah i noticed that as well. Good news is he said hes only adding around 30 books to the database. Another issue with adding that many is the current max size is 1024. I don't believe that we will have to deal with more than that though so we _should_ be fine.
